name: "Inclui comentário (Composite)"
description: "Essa action inclui comentário em issues ou PRs (Composite)"
author: "Fabricio Veronez"
inputs:
  GITHUB_TOKEN:
    description: "Token de acesso ao GitHub"
    required: true
  issue-id:
    description: "ID da issue ou PR"
    required: true
  comment:
    description: "Comentário a ser incluído"
    required: true
  GITHUB_REPOSITORY:
    description: "Id do repositório"
outputs:
  comment-id:
    description: "ID do comentário incluído"
branding:
  icon: 'archive'
  color: 'gray-black'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '${{ inputs.GITHUB_TOKEN }}'
    - '${{ inputs.issue-id }}'
    - '${{ inputs.comment }}'
    - '${{ inputs.GITHUB_REPOSITORY }}'
